version: '3'
services:
  #myapplication:
  #  image: mongodb/mongodb-community-server:6.0-ubi8
  #  environment:
  #    - CONN_STR=mongodb://user:pass@mongodb
  #  command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
  #  depends_on:
  #    - mongodb
  mongo:
    image: mongo
    ports:
      - 27017:27017
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: locater
      MONGO_INITDB_ROOT_PASSWORD: pwdpwd

  mongo-express:
    image: mongo-express
    #restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: locater
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwdpwd
      ME_CONFIG_MONGODB_URL: mongodb://locater:pwdpwd@mongo:27017/
      #ME_CONFIG_BASICAUTH: false